export const EVENTS = [
    {
        img: '/event1.jpg',
        name: 'DevXperience',
        date: '12 Jan 2024',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Impedit, repudiandae doloremque sint laboriosam architecto porro non velit libero quis officia quo error exercitationem accusantium?'
    },
    {
        img: '/event1.jpg',
        name: 'DevXperience',
        date: '12 Jan 2024',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Impedit, repudiandae doloremque sint laboriosam architecto porro non velit libero quis officia quo error exercitationem accusantium?'
    },
    {
        img: '/event1.jpg',
        name: 'DevXperience',
        date: '12 Jan 2024',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Impedit, repudiandae doloremque sint laboriosam architecto porro non velit libero quis officia quo error exercitationem accusantium?'
    },
];

export const IMGS = [
    '/1.JPG',
    '/2.JPG',
    '/3.JPG',
    '/4.jpg',
    '/5.jpg',
    '/6.jpg',
    '/7.jpg',
    '/1.JPG',
    '/2.JPG',
    '/3.JPG',
    '/4.jpg',
    '/5.jpg',
    '/6.jpg',
    '/7.jpg',
    '/1.JPG',
    '/2.JPG',
    '/3.JPG',
    '/4.jpg',
    '/5.jpg',
    '/6.jpg',
    '/7.jpg',
    '/1.JPG',
    '/2.JPG',
    '/3.JPG',
    '/4.jpg',
    '/5.jpg',
    '/6.jpg',
    '/7.jpg',
    '/1.JPG',
    '/2.JPG',
    '/3.JPG',
    '/4.jpg',
    '/5.jpg',
    '/6.jpg',
    '/7.jpg',
    '/1.JPG',
    '/2.JPG',
    '/3.JPG',
    '/4.jpg',
    '/5.jpg',
    '/6.jpg',
    '/7.jpg',
];